linters:
  enable:
    - gofmt
    - goimports
    - gosec
    - bodyclose
    - misspell
    - revive
    - gosimple
linters-settings:
  revive:
    rules:
      - name: cyclomatic
        severity: warning
        disabled: false
        arguments: [10]

output:
  formats:
    - format: "colored-line-number"
  print-issued-lines: true
  print-linter-name: true
