linters:
  enable:
    - gofmt
    - goimports
    - gosec
    - bodyclose
    - misspell
    - revive
linters-settings:
  revive:
    rules:
      - name: cyclomatic
        severity: warning
        disabled: false
        arguments: [10]

output:
  format: "colored-line-number"
  print-issued-lines: true
  print-linter-name: true
