basePath: /
definitions:
  handler.createPdfFromHTMLRequest:
    properties:
      html:
        type: string
    required:
    - html
    type: object
  utils.Error:
    properties:
      errors:
        additionalProperties: true
        type: object
    type: object
info:
  contact:
    email: anibaldeboni@gmail.com
    name: Aníbal Deboni Neto
  description: This documentation for One-Eyed-Willy pdf generator.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: One-Eyed-Willy pdf generation API
  version: "1.0"
paths:
  /pdf/generate:
    post:
      consumes:
      - applcation/json
      description: Generate a new pdf file from a html string
      parameters:
      - description: Base64 encoded string of a html
        in: body
        name: html
        required: true
        schema:
          $ref: '#/definitions/handler.createPdfFromHTMLRequest'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: Create a pdf
      tags:
      - pdf
  /pdf/merge:
    post:
      consumes:
      - multipart/form-data
      description: Merges two or more pdfs
      parameters:
      - description: pdf files to merge
        in: formData
        name: files
        required: true
        type: file
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: Merge pdfs
      tags:
      - pdf
schemes:
- http
- https
swagger: "2.0"
