on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_call:

permissions:
  id-token: write
  contents: write
  issues: read
  checks: write
  actions: read
  security-events: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  basic-checks:
    uses: ./.github/workflows/basic-checks.yml
    secrets: inherit
  code-analysis:
    uses: ./.github/workflows/codeql.yml
    secrets: inherit
  code-quality:
    uses: ./.github/workflows/code-quality.yml
    secrets: inherit
    needs: [basic-checks, code-analysis]
