on:
  push:
    branches-ignore:
      - staging
      - master

permissions:
  id-token: write
  contents: write
  issues: read
  checks: write
  actions: read
  security-events: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit
  code-analysis:
    uses: ./.github/workflows/codeql.yml
    secrets: inherit
