name: Run linter and unit tests
on: workflow_call

env:
  LATEST_GO_VERSION: "1.20"
jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.18", "1.19", "1.20"]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: v1.53

      - name: Run Tests
        run: go test -race --coverprofile=coverage.coverprofile --covermode=atomic ./...

      - name: Store unit test coverage data
        if: success() && matrix.go-version == env.LATEST_GO_VERSION
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-coverage
          path: coverage.coverprofile
          retention-days: 1
